export const main_subjects = [
  [
    { title: "HTML", totalSkills: 17, learnedSkills: 0 },
    [
      { title: "Elements", learned: false },
      { title: "Paragraphs", learned: false },
      { title: "Headings", learned: false },
      { title: "Links", learned: false },
      { title: "Attributes", learned: false },
      { title: "Formatting", learned: false },
      { title: "Comments", learned: false },
      { title: "Images", learned: false },
      { title: "Tables", learned: false },
      { title: "Lists", learned: false },
      { title: "Classes", learned: false },
      { title: "Id", learned: false },
      { title: "Iframes", learned: false },
      { title: "File paths", learned: false },
      { title: "Head", learned: false },
      { title: "Layout", learned: false },
      { title: "Semantics", learned: false },
      { title: "Charset", learned: false },
    ],
  ],
  [
    { title: "CSS", totalSkills: 39, learnedSkills: 0 },
    [
      { title: "Syntax", learned: false },
      { title: "Selectors", learned: false },
      { title: "Comments", learned: false },
      { title: "Colors", learned: false },
      { title: "Backgrounds", learned: false },
      { title: "Borders", learned: false },
      { title: "Margins", learned: false },
      { title: "Padding", learned: false },
      { title: "Height", learned: false },
      { title: "Width", learned: false },
      { title: "Box model", learned: false },
      { title: "Outline", learned: false },
      { title: "Text", learned: false },
      { title: "Fonts", learned: false },
      { title: "Icons", learned: false },
      { title: "Links", learned: false },
      { title: "Lists", learned: false },
      { title: "Tables", learned: false },
      { title: "Display", learned: false },
      { title: "Max", learned: false },
      { title: "Position", learned: false },
      { title: "Overflow", learned: false },
      { title: "Inline", learned: false },
      { title: "Align", learned: false },
      { title: "Psuedo-class", learned: false },
      { title: "Psuedo-element", learned: false },
      { title: "Opacity", learned: false },
      { title: "Navigation", learned: false },
      { title: "Dropdown", learned: false },
      { title: "Image", learned: false },
      { title: "!important", learned: false },
      { title: "Gradient", learned: false },
      { title: "Shadow", learned: false },
      { title: "Transition", learned: false },
      { title: "Animation", learned: false },
      { title: "Button", learned: false },
      { title: "Media queries", learned: false },
      { title: "Flexbox", learned: false },
      { title: "Grid", learned: false },
    ],
  ],
  [
    { title: "JavaScript", totalSkills: 45, learnedSkills: 0 },
    [
      { title: "Syntax", learned: false },
      { title: "Comments", learned: false },
      { title: "Variables", learned: false },
      { title: "Let", learned: false },
      { title: "Const", learned: false },
      { title: "Operators", learned: false },
      { title: "Arithmetic", learned: false },
      { title: "Assignment", learned: false },
      { title: "Data types", learned: false },
      { title: "Functions", learned: false },
      { title: "Objects", learned: false },
      { title: "Events", learned: false },
      { title: "Strings", learned: false },
      { title: "String methods", learned: false },
      { title: "Numbers", learned: false },
      { title: "Number methods", learned: false },
      { title: "Arrays", learned: false },
      { title: "Array methods", learned: false },
      { title: "Array sort", learned: false },
      { title: "Array Iteration", learned: false },
      { title: "Dates", learned: false },
      { title: "Math", learned: false },
      { title: "Random", learned: false },
      { title: "Booleans", learned: false },
      { title: "Comparisons", learned: false },
      { title: "Conditions", learned: false },
      { title: "Switch", learned: false },
      { title: "Loop For", learned: false },
      { title: "Loop For In", learned: false },
      { title: "Loop For Of", learned: false },
      { title: "Loop While", learned: false },
      { title: "Break", learned: false },
      { title: "RegExp", learned: false },
      { title: "Errors", learned: false },
      { title: "Scope", learned: false },
      { title: "Hoisting", learned: false },
      { title: "Strict Mode", learned: false },
      { title: "this Keyword", learned: false },
      { title: "Classes", learned: false },
      { title: "JSON", learned: false },
      { title: "Debugging", learned: false },
      { title: "Asynchronous", learned: false },
      { title: "Promises", learned: false },
      { title: "Async-Await", learned: false },
      { title: "Fetch", learned: false },
    ],
  ],
  [
    { title: "React", totalSkills: 14, learnedSkills: 0 },
    [
      { title: "ES6", learned: false },
      { title: "Render", learned: false },
      { title: "JSX", learned: false },
      { title: "Components", learned: false },
      { title: "Props", learned: false },
      { title: "State", learned: false },
      { title: "Hooks", learned: false },
      { title: "Lifecycle", learned: false },
      { title: "Events", learned: false },
      { title: "Forms", learned: false },
      { title: "CSS", learned: false },
      { title: "Map", learned: false },
      { title: "Filter", learned: false },
      { title: "Reduce", learned: false },
    ],
  ],
];
export const secondary_subjects = [
  [
    { title: "Git", totalSkills: 7, learnedSkills: 0 },
    [
      { title: "Github", learned: false },
      { title: "Push", learned: false },
      { title: "Pull", learned: false },
      { title: "Commit", learned: false },
      { title: "Branch", learned: false },
      { title: "Merge", learned: false },
      { title: "Terminal commands", learned: false },
    ],
  ],
  [
    { title: "Terminal", totalSkills: 6, learnedSkills: 0 },
    [
      { title: "Bash", learned: false },
      { title: "cd", learned: false },
      { title: "ls", learned: false },
      { title: "git", learned: false },
      { title: "npm", learned: false },
      { title: "dir", learned: false },
    ],
  ],
  [
    { title: "Design tool", totalSkills: 6, learnedSkills: 0 },
    [
      { title: "Adobe XD", learned: false },
      { title: "Sketch", learned: false },
      { title: "Figma", learned: false },
      { title: "Mockup", learned: false },
      { title: "Prototype", learned: false },
      { title: "Wireframe", learned: false },
    ],
  ],
  [
    { title: "Deployment", totalSkills: 6, learnedSkills: 0 },
    [
      { title: "Heroku", learned: false },
      { title: "Netlify", learned: false },
      { title: "AWS", learned: false },
      { title: "FTP", learned: false },
      { title: "Web host", learned: false },
      { title: "Domain", learned: false },
    ],
  ],
  [
    { title: "VSCode", totalSkills: 6, learnedSkills: 0 },
    [
      { title: "Prettier", learned: false },
      { title: "Lint", learned: false },
      { title: "Keyboard shortcuts", learned: false },
      { title: "Live server", learned: false },
      { title: "Debugging", learned: false },
      { title: "Git", learned: false },
    ],
  ],
  [
    { title: "Web browser", totalSkills: 7, learnedSkills: 0 },
    [
      { title: "Chrome", learned: false },
      { title: "Dev tools", learned: false },
      { title: "Cookie", learned: false },
      { title: "Sessions", learned: false },
      { title: "Local storage", learned: false },
      { title: "HTTPS", learned: false },
      { title: "Loading time", learned: false },
    ],
  ],
];
